Use debuild for build deps
* Transfer install-build-deps hook from gbp to debuild
* Fail installing build deps fast if no d/control file

Signed-off-by: Tyler Heucke <tyler.heucke@dell.com>

diff --git a/assets/install-build-deps b/assets/install-build-deps
--- a/assets/install-build-deps
+++ b/assets/install-build-deps
@@ -1,6 +1,16 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
+# fail fast if possible
+if [[ $# -eq 0 ]] && [[ ! -e ./debian/control ]]; then
+  echo "./debian/control" does not exist. Nothing to do.
+  exit 1
+fi
+if [[ $# -eq 1 ]] && [[ ! -e $1/debian/control ]]; then
+  echo "$1/debian/control" does not exist. Nothing to do.
+  exit 1
+fi
+
 if [[ -n "${EXTRA_SOURCES}" ]]; then
   echo "${EXTRA_SOURCES}" | sudo tee /etc/apt/sources.list.d/20extra.list >/dev/null
 fi
@@ -20,7 +30,7 @@ sudo mkdir -p "$REPO"
 apt-ftparchive packages ../../../$DEBS 2>/dev/null | sudo tee $REPO/Packages >/dev/null
 apt-ftparchive sources ../../../$DEBS 2>/dev/null | sudo tee $REPO/Sources >/dev/null
 apt-ftparchive release $REPO 2>/dev/null | sudo tee $REPO/Release >/dev/null
-sudo apt-get update
+sudo apt-get -qq update
 
 # Support any number of arguments
 if [[ $# -eq 0 ]]; then
